# Generated by Django 5.2.12 on 2026-03-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Developer'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
